apiVersion: ray.io/v1
kind: RayService
metadata:
  name: ray-serve-llm
spec:
  serveConfigV2: |
    applications:
    - name: llm
      import_path: ray.serve.llm:build_openai_app
      route_prefix: "/"
      args:
        llm_configs:
        - model_loading_config:
            model_id: Qwen/Qwen3-32B-AWQ
            model_source: Qwen/Qwen3-32B-AWQ
          deployment_config:
            autoscaling_config:
              min_replicas: 1
              max_replicas: 1
          engine_kwargs:
            tensor_parallel_size: 1
            pipeline_parallel_size: 2
            quantization: awq
  rayClusterConfig:
    rayVersion: "2.50.1"
    headGroupSpec:
      rayStartParams:
        num-gpus: "0"
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray-llm:2.50.1-py311-cu128
            ports:
            - containerPort: 8000
              name: serve
            - containerPort: 8080
              name: metrics
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              requests:
                cpu: 2
                memory: 16Gi
    workerGroupSpecs:
    - replicas: 2
      minReplicas: 2
      maxReplicas: 2
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          tolerations:
          - key: nvidia.com/gpu
            operator: Equal
            value: "true"
            effect: NoSchedule
          containers:
          - name: ray-worker
            image: rayproject/ray-llm:2.50.1-py311-cu128
            env:
            resources:
              requests:
                cpu: 28
                memory: 100Gi
                nvidia.com/gpu: "1"
                # vpc.amazonaws.com/efa: "1"
              limits:
                cpu: 28
                memory: 100Gi
                nvidia.com/gpu: "1"
                # vpc.amazonaws.com/efa: "1"