[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface>=0.0.1",
    "ragas>=0.4.2",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=5.2.0",
    "typer>=0.21.0",
]
